name: MLOps Azure Pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install numpy tensorflow pillow

      - name: Check training script syntax
        run: |
          python -m py_compile mlops-labs/components/training/code/train.py
